// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1100300_HeroMessage.proto

#ifndef PROTOBUF_1100300_5fHeroMessage_2eproto__INCLUDED
#define PROTOBUF_1100300_5fHeroMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

class SlotInfoBean;
class EquipmentInfoBean;
class HeroInfoBean;
class ChangeToStoneKeyIdBean;
class GetHeroInfoUp;
class GetHeroInfoDown;
class UseHeroBookUp;
class UseHeroBookDown;
class CallHeroUp;
class HeroEvolutionUp;
class HeroTrainUp;
class HeroTrainDown;
class SaveTrainPatienceUp;
class CancelTrainPatienceUp;

enum HeroCommondIdEnum {
  _GetHeroInfoUp = 1100301,
  _GetHeroInfoDown = 1100302,
  _UseHeroBookUp = 1100303,
  _UseHeroBookDown = 1100304,
  _CallHeroUp = 1100305,
  _CallHeroDown = 1100306,
  _HeroEvolutionUp = 1100307,
  _HeroTrainUp = 1100309,
  _HeroTrainDown = 1100310,
  _SaveTrainPatienceUp = 1100311,
  _CancelTrainPatienceUp = 1100313
};
bool HeroCommondIdEnum_IsValid(int value);
const HeroCommondIdEnum HeroCommondIdEnum_MIN = _GetHeroInfoUp;
const HeroCommondIdEnum HeroCommondIdEnum_MAX = _CancelTrainPatienceUp;
const int HeroCommondIdEnum_ARRAYSIZE = HeroCommondIdEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* HeroCommondIdEnum_descriptor();
inline const ::std::string& HeroCommondIdEnum_Name(HeroCommondIdEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    HeroCommondIdEnum_descriptor(), value);
}
inline bool HeroCommondIdEnum_Parse(
    const ::std::string& name, HeroCommondIdEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<HeroCommondIdEnum>(
    HeroCommondIdEnum_descriptor(), name, value);
}
// ===================================================================

class SlotInfoBean : public ::google::protobuf::Message {
 public:
  SlotInfoBean();
  virtual ~SlotInfoBean();

  SlotInfoBean(const SlotInfoBean& from);

  inline SlotInfoBean& operator=(const SlotInfoBean& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SlotInfoBean& default_instance();

  void Swap(SlotInfoBean* other);

  // implements Message ----------------------------------------------

  SlotInfoBean* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SlotInfoBean& from);
  void MergeFrom(const SlotInfoBean& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required uint32 plugId = 2;
  inline bool has_plugid() const;
  inline void clear_plugid();
  static const int kPlugIdFieldNumber = 2;
  inline ::google::protobuf::uint32 plugid() const;
  inline void set_plugid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SlotInfoBean)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_plugid();
  inline void clear_has_plugid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 plugid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static SlotInfoBean* default_instance_;
};
// -------------------------------------------------------------------

class EquipmentInfoBean : public ::google::protobuf::Message {
 public:
  EquipmentInfoBean();
  virtual ~EquipmentInfoBean();

  EquipmentInfoBean(const EquipmentInfoBean& from);

  inline EquipmentInfoBean& operator=(const EquipmentInfoBean& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EquipmentInfoBean& default_instance();

  void Swap(EquipmentInfoBean* other);

  // implements Message ----------------------------------------------

  EquipmentInfoBean* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EquipmentInfoBean& from);
  void MergeFrom(const EquipmentInfoBean& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 positionId = 1;
  inline bool has_positionid() const;
  inline void clear_positionid();
  static const int kPositionIdFieldNumber = 1;
  inline ::google::protobuf::uint32 positionid() const;
  inline void set_positionid(::google::protobuf::uint32 value);

  // required uint32 level = 2;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 2;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // required uint32 quality = 3;
  inline bool has_quality() const;
  inline void clear_quality();
  static const int kQualityFieldNumber = 3;
  inline ::google::protobuf::uint32 quality() const;
  inline void set_quality(::google::protobuf::uint32 value);

  // repeated .SlotInfoBean slotInfoBean = 4;
  inline int slotinfobean_size() const;
  inline void clear_slotinfobean();
  static const int kSlotInfoBeanFieldNumber = 4;
  inline const ::SlotInfoBean& slotinfobean(int index) const;
  inline ::SlotInfoBean* mutable_slotinfobean(int index);
  inline ::SlotInfoBean* add_slotinfobean();
  inline const ::google::protobuf::RepeatedPtrField< ::SlotInfoBean >&
      slotinfobean() const;
  inline ::google::protobuf::RepeatedPtrField< ::SlotInfoBean >*
      mutable_slotinfobean();

  // @@protoc_insertion_point(class_scope:EquipmentInfoBean)
 private:
  inline void set_has_positionid();
  inline void clear_has_positionid();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_quality();
  inline void clear_has_quality();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 positionid_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::RepeatedPtrField< ::SlotInfoBean > slotinfobean_;
  ::google::protobuf::uint32 quality_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static EquipmentInfoBean* default_instance_;
};
// -------------------------------------------------------------------

class HeroInfoBean : public ::google::protobuf::Message {
 public:
  HeroInfoBean();
  virtual ~HeroInfoBean();

  HeroInfoBean(const HeroInfoBean& from);

  inline HeroInfoBean& operator=(const HeroInfoBean& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroInfoBean& default_instance();

  void Swap(HeroInfoBean* other);

  // implements Message ----------------------------------------------

  HeroInfoBean* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroInfoBean& from);
  void MergeFrom(const HeroInfoBean& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required uint32 level = 2;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 2;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // required uint32 experience = 3;
  inline bool has_experience() const;
  inline void clear_experience();
  static const int kExperienceFieldNumber = 3;
  inline ::google::protobuf::uint32 experience() const;
  inline void set_experience(::google::protobuf::uint32 value);

  // required uint32 star = 4;
  inline bool has_star() const;
  inline void clear_star();
  static const int kStarFieldNumber = 4;
  inline ::google::protobuf::uint32 star() const;
  inline void set_star(::google::protobuf::uint32 value);

  // required uint32 quality = 5;
  inline bool has_quality() const;
  inline void clear_quality();
  static const int kQualityFieldNumber = 5;
  inline ::google::protobuf::uint32 quality() const;
  inline void set_quality(::google::protobuf::uint32 value);

  // repeated uint32 currentPatience = 6;
  inline int currentpatience_size() const;
  inline void clear_currentpatience();
  static const int kCurrentPatienceFieldNumber = 6;
  inline ::google::protobuf::uint32 currentpatience(int index) const;
  inline void set_currentpatience(int index, ::google::protobuf::uint32 value);
  inline void add_currentpatience(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      currentpatience() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_currentpatience();

  // required bool isSave = 7;
  inline bool has_issave() const;
  inline void clear_issave();
  static const int kIsSaveFieldNumber = 7;
  inline bool issave() const;
  inline void set_issave(bool value);

  // required uint32 trainType = 8;
  inline bool has_traintype() const;
  inline void clear_traintype();
  static const int kTrainTypeFieldNumber = 8;
  inline ::google::protobuf::uint32 traintype() const;
  inline void set_traintype(::google::protobuf::uint32 value);

  // repeated uint32 waitPatience = 9;
  inline int waitpatience_size() const;
  inline void clear_waitpatience();
  static const int kWaitPatienceFieldNumber = 9;
  inline ::google::protobuf::uint32 waitpatience(int index) const;
  inline void set_waitpatience(int index, ::google::protobuf::uint32 value);
  inline void add_waitpatience(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      waitpatience() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_waitpatience();

  // repeated .EquipmentInfoBean equipmentInfoBean = 10;
  inline int equipmentinfobean_size() const;
  inline void clear_equipmentinfobean();
  static const int kEquipmentInfoBeanFieldNumber = 10;
  inline const ::EquipmentInfoBean& equipmentinfobean(int index) const;
  inline ::EquipmentInfoBean* mutable_equipmentinfobean(int index);
  inline ::EquipmentInfoBean* add_equipmentinfobean();
  inline const ::google::protobuf::RepeatedPtrField< ::EquipmentInfoBean >&
      equipmentinfobean() const;
  inline ::google::protobuf::RepeatedPtrField< ::EquipmentInfoBean >*
      mutable_equipmentinfobean();

  // @@protoc_insertion_point(class_scope:HeroInfoBean)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_experience();
  inline void clear_has_experience();
  inline void set_has_star();
  inline void clear_has_star();
  inline void set_has_quality();
  inline void clear_has_quality();
  inline void set_has_issave();
  inline void clear_has_issave();
  inline void set_has_traintype();
  inline void clear_has_traintype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 experience_;
  ::google::protobuf::uint32 star_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > currentpatience_;
  ::google::protobuf::uint32 quality_;
  bool issave_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > waitpatience_;
  ::google::protobuf::RepeatedPtrField< ::EquipmentInfoBean > equipmentinfobean_;
  ::google::protobuf::uint32 traintype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static HeroInfoBean* default_instance_;
};
// -------------------------------------------------------------------

class ChangeToStoneKeyIdBean : public ::google::protobuf::Message {
 public:
  ChangeToStoneKeyIdBean();
  virtual ~ChangeToStoneKeyIdBean();

  ChangeToStoneKeyIdBean(const ChangeToStoneKeyIdBean& from);

  inline ChangeToStoneKeyIdBean& operator=(const ChangeToStoneKeyIdBean& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChangeToStoneKeyIdBean& default_instance();

  void Swap(ChangeToStoneKeyIdBean* other);

  // implements Message ----------------------------------------------

  ChangeToStoneKeyIdBean* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChangeToStoneKeyIdBean& from);
  void MergeFrom(const ChangeToStoneKeyIdBean& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 itemKeyId = 1;
  inline bool has_itemkeyid() const;
  inline void clear_itemkeyid();
  static const int kItemKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 itemkeyid() const;
  inline void set_itemkeyid(::google::protobuf::uint32 value);

  // required uint32 count = 2;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 2;
  inline ::google::protobuf::uint32 count() const;
  inline void set_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ChangeToStoneKeyIdBean)
 private:
  inline void set_has_itemkeyid();
  inline void clear_has_itemkeyid();
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 itemkeyid_;
  ::google::protobuf::uint32 count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static ChangeToStoneKeyIdBean* default_instance_;
};
// -------------------------------------------------------------------

class GetHeroInfoUp : public ::google::protobuf::Message {
 public:
  GetHeroInfoUp();
  virtual ~GetHeroInfoUp();

  GetHeroInfoUp(const GetHeroInfoUp& from);

  inline GetHeroInfoUp& operator=(const GetHeroInfoUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetHeroInfoUp& default_instance();

  void Swap(GetHeroInfoUp* other);

  // implements Message ----------------------------------------------

  GetHeroInfoUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetHeroInfoUp& from);
  void MergeFrom(const GetHeroInfoUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string userId = 1;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 1;
  inline const ::std::string& userid() const;
  inline void set_userid(const ::std::string& value);
  inline void set_userid(const char* value);
  inline void set_userid(const char* value, size_t size);
  inline ::std::string* mutable_userid();
  inline ::std::string* release_userid();
  inline void set_allocated_userid(::std::string* userid);

  // @@protoc_insertion_point(class_scope:GetHeroInfoUp)
 private:
  inline void set_has_userid();
  inline void clear_has_userid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* userid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static GetHeroInfoUp* default_instance_;
};
// -------------------------------------------------------------------

class GetHeroInfoDown : public ::google::protobuf::Message {
 public:
  GetHeroInfoDown();
  virtual ~GetHeroInfoDown();

  GetHeroInfoDown(const GetHeroInfoDown& from);

  inline GetHeroInfoDown& operator=(const GetHeroInfoDown& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetHeroInfoDown& default_instance();

  void Swap(GetHeroInfoDown* other);

  // implements Message ----------------------------------------------

  GetHeroInfoDown* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetHeroInfoDown& from);
  void MergeFrom(const GetHeroInfoDown& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string userId = 1;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 1;
  inline const ::std::string& userid() const;
  inline void set_userid(const ::std::string& value);
  inline void set_userid(const char* value);
  inline void set_userid(const char* value, size_t size);
  inline ::std::string* mutable_userid();
  inline ::std::string* release_userid();
  inline void set_allocated_userid(::std::string* userid);

  // required uint32 heroExp = 2;
  inline bool has_heroexp() const;
  inline void clear_heroexp();
  static const int kHeroExpFieldNumber = 2;
  inline ::google::protobuf::uint32 heroexp() const;
  inline void set_heroexp(::google::protobuf::uint32 value);

  // repeated .HeroInfoBean heroInfoBean = 3;
  inline int heroinfobean_size() const;
  inline void clear_heroinfobean();
  static const int kHeroInfoBeanFieldNumber = 3;
  inline const ::HeroInfoBean& heroinfobean(int index) const;
  inline ::HeroInfoBean* mutable_heroinfobean(int index);
  inline ::HeroInfoBean* add_heroinfobean();
  inline const ::google::protobuf::RepeatedPtrField< ::HeroInfoBean >&
      heroinfobean() const;
  inline ::google::protobuf::RepeatedPtrField< ::HeroInfoBean >*
      mutable_heroinfobean();

  // @@protoc_insertion_point(class_scope:GetHeroInfoDown)
 private:
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_heroexp();
  inline void clear_has_heroexp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* userid_;
  ::google::protobuf::RepeatedPtrField< ::HeroInfoBean > heroinfobean_;
  ::google::protobuf::uint32 heroexp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static GetHeroInfoDown* default_instance_;
};
// -------------------------------------------------------------------

class UseHeroBookUp : public ::google::protobuf::Message {
 public:
  UseHeroBookUp();
  virtual ~UseHeroBookUp();

  UseHeroBookUp(const UseHeroBookUp& from);

  inline UseHeroBookUp& operator=(const UseHeroBookUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UseHeroBookUp& default_instance();

  void Swap(UseHeroBookUp* other);

  // implements Message ----------------------------------------------

  UseHeroBookUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UseHeroBookUp& from);
  void MergeFrom(const UseHeroBookUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 itemId = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIdFieldNumber = 1;
  inline ::google::protobuf::uint32 itemid() const;
  inline void set_itemid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:UseHeroBookUp)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 itemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static UseHeroBookUp* default_instance_;
};
// -------------------------------------------------------------------

class UseHeroBookDown : public ::google::protobuf::Message {
 public:
  UseHeroBookDown();
  virtual ~UseHeroBookDown();

  UseHeroBookDown(const UseHeroBookDown& from);

  inline UseHeroBookDown& operator=(const UseHeroBookDown& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UseHeroBookDown& default_instance();

  void Swap(UseHeroBookDown* other);

  // implements Message ----------------------------------------------

  UseHeroBookDown* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UseHeroBookDown& from);
  void MergeFrom(const UseHeroBookDown& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool isHaveHero = 1;
  inline bool has_ishavehero() const;
  inline void clear_ishavehero();
  static const int kIsHaveHeroFieldNumber = 1;
  inline bool ishavehero() const;
  inline void set_ishavehero(bool value);

  // required uint32 heroKeyId = 2;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 2;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // optional .ChangeToStoneKeyIdBean changeToStoneKeyIdBean = 3;
  inline bool has_changetostonekeyidbean() const;
  inline void clear_changetostonekeyidbean();
  static const int kChangeToStoneKeyIdBeanFieldNumber = 3;
  inline const ::ChangeToStoneKeyIdBean& changetostonekeyidbean() const;
  inline ::ChangeToStoneKeyIdBean* mutable_changetostonekeyidbean();
  inline ::ChangeToStoneKeyIdBean* release_changetostonekeyidbean();
  inline void set_allocated_changetostonekeyidbean(::ChangeToStoneKeyIdBean* changetostonekeyidbean);

  // @@protoc_insertion_point(class_scope:UseHeroBookDown)
 private:
  inline void set_has_ishavehero();
  inline void clear_has_ishavehero();
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();
  inline void set_has_changetostonekeyidbean();
  inline void clear_has_changetostonekeyidbean();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool ishavehero_;
  ::google::protobuf::uint32 herokeyid_;
  ::ChangeToStoneKeyIdBean* changetostonekeyidbean_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static UseHeroBookDown* default_instance_;
};
// -------------------------------------------------------------------

class CallHeroUp : public ::google::protobuf::Message {
 public:
  CallHeroUp();
  virtual ~CallHeroUp();

  CallHeroUp(const CallHeroUp& from);

  inline CallHeroUp& operator=(const CallHeroUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CallHeroUp& default_instance();

  void Swap(CallHeroUp* other);

  // implements Message ----------------------------------------------

  CallHeroUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CallHeroUp& from);
  void MergeFrom(const CallHeroUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heroKeyId = 1;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CallHeroUp)
 private:
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 herokeyid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static CallHeroUp* default_instance_;
};
// -------------------------------------------------------------------

class HeroEvolutionUp : public ::google::protobuf::Message {
 public:
  HeroEvolutionUp();
  virtual ~HeroEvolutionUp();

  HeroEvolutionUp(const HeroEvolutionUp& from);

  inline HeroEvolutionUp& operator=(const HeroEvolutionUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroEvolutionUp& default_instance();

  void Swap(HeroEvolutionUp* other);

  // implements Message ----------------------------------------------

  HeroEvolutionUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroEvolutionUp& from);
  void MergeFrom(const HeroEvolutionUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heroKeyId = 1;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:HeroEvolutionUp)
 private:
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 herokeyid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static HeroEvolutionUp* default_instance_;
};
// -------------------------------------------------------------------

class HeroTrainUp : public ::google::protobuf::Message {
 public:
  HeroTrainUp();
  virtual ~HeroTrainUp();

  HeroTrainUp(const HeroTrainUp& from);

  inline HeroTrainUp& operator=(const HeroTrainUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroTrainUp& default_instance();

  void Swap(HeroTrainUp* other);

  // implements Message ----------------------------------------------

  HeroTrainUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroTrainUp& from);
  void MergeFrom(const HeroTrainUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heroKeyId = 1;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // required uint32 trainType = 2;
  inline bool has_traintype() const;
  inline void clear_traintype();
  static const int kTrainTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 traintype() const;
  inline void set_traintype(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:HeroTrainUp)
 private:
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();
  inline void set_has_traintype();
  inline void clear_has_traintype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 herokeyid_;
  ::google::protobuf::uint32 traintype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static HeroTrainUp* default_instance_;
};
// -------------------------------------------------------------------

class HeroTrainDown : public ::google::protobuf::Message {
 public:
  HeroTrainDown();
  virtual ~HeroTrainDown();

  HeroTrainDown(const HeroTrainDown& from);

  inline HeroTrainDown& operator=(const HeroTrainDown& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroTrainDown& default_instance();

  void Swap(HeroTrainDown* other);

  // implements Message ----------------------------------------------

  HeroTrainDown* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroTrainDown& from);
  void MergeFrom(const HeroTrainDown& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heroKeyId = 1;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // repeated uint32 patiences = 2;
  inline int patiences_size() const;
  inline void clear_patiences();
  static const int kPatiencesFieldNumber = 2;
  inline ::google::protobuf::uint32 patiences(int index) const;
  inline void set_patiences(int index, ::google::protobuf::uint32 value);
  inline void add_patiences(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      patiences() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_patiences();

  // @@protoc_insertion_point(class_scope:HeroTrainDown)
 private:
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > patiences_;
  ::google::protobuf::uint32 herokeyid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static HeroTrainDown* default_instance_;
};
// -------------------------------------------------------------------

class SaveTrainPatienceUp : public ::google::protobuf::Message {
 public:
  SaveTrainPatienceUp();
  virtual ~SaveTrainPatienceUp();

  SaveTrainPatienceUp(const SaveTrainPatienceUp& from);

  inline SaveTrainPatienceUp& operator=(const SaveTrainPatienceUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SaveTrainPatienceUp& default_instance();

  void Swap(SaveTrainPatienceUp* other);

  // implements Message ----------------------------------------------

  SaveTrainPatienceUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SaveTrainPatienceUp& from);
  void MergeFrom(const SaveTrainPatienceUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heroKeyId = 1;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SaveTrainPatienceUp)
 private:
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 herokeyid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static SaveTrainPatienceUp* default_instance_;
};
// -------------------------------------------------------------------

class CancelTrainPatienceUp : public ::google::protobuf::Message {
 public:
  CancelTrainPatienceUp();
  virtual ~CancelTrainPatienceUp();

  CancelTrainPatienceUp(const CancelTrainPatienceUp& from);

  inline CancelTrainPatienceUp& operator=(const CancelTrainPatienceUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CancelTrainPatienceUp& default_instance();

  void Swap(CancelTrainPatienceUp* other);

  // implements Message ----------------------------------------------

  CancelTrainPatienceUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CancelTrainPatienceUp& from);
  void MergeFrom(const CancelTrainPatienceUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 heroKeyId = 1;
  inline bool has_herokeyid() const;
  inline void clear_herokeyid();
  static const int kHeroKeyIdFieldNumber = 1;
  inline ::google::protobuf::uint32 herokeyid() const;
  inline void set_herokeyid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CancelTrainPatienceUp)
 private:
  inline void set_has_herokeyid();
  inline void clear_has_herokeyid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 herokeyid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_AssignDesc_1100300_5fHeroMessage_2eproto();
  friend void protobuf_ShutdownFile_1100300_5fHeroMessage_2eproto();

  void InitAsDefaultInstance();
  static CancelTrainPatienceUp* default_instance_;
};
// ===================================================================


// ===================================================================

// SlotInfoBean

// required uint32 id = 1;
inline bool SlotInfoBean::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SlotInfoBean::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SlotInfoBean::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SlotInfoBean::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 SlotInfoBean::id() const {
  return id_;
}
inline void SlotInfoBean::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required uint32 plugId = 2;
inline bool SlotInfoBean::has_plugid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SlotInfoBean::set_has_plugid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SlotInfoBean::clear_has_plugid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SlotInfoBean::clear_plugid() {
  plugid_ = 0u;
  clear_has_plugid();
}
inline ::google::protobuf::uint32 SlotInfoBean::plugid() const {
  return plugid_;
}
inline void SlotInfoBean::set_plugid(::google::protobuf::uint32 value) {
  set_has_plugid();
  plugid_ = value;
}

// -------------------------------------------------------------------

// EquipmentInfoBean

// required uint32 positionId = 1;
inline bool EquipmentInfoBean::has_positionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EquipmentInfoBean::set_has_positionid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EquipmentInfoBean::clear_has_positionid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EquipmentInfoBean::clear_positionid() {
  positionid_ = 0u;
  clear_has_positionid();
}
inline ::google::protobuf::uint32 EquipmentInfoBean::positionid() const {
  return positionid_;
}
inline void EquipmentInfoBean::set_positionid(::google::protobuf::uint32 value) {
  set_has_positionid();
  positionid_ = value;
}

// required uint32 level = 2;
inline bool EquipmentInfoBean::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EquipmentInfoBean::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EquipmentInfoBean::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EquipmentInfoBean::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 EquipmentInfoBean::level() const {
  return level_;
}
inline void EquipmentInfoBean::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
}

// required uint32 quality = 3;
inline bool EquipmentInfoBean::has_quality() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EquipmentInfoBean::set_has_quality() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EquipmentInfoBean::clear_has_quality() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EquipmentInfoBean::clear_quality() {
  quality_ = 0u;
  clear_has_quality();
}
inline ::google::protobuf::uint32 EquipmentInfoBean::quality() const {
  return quality_;
}
inline void EquipmentInfoBean::set_quality(::google::protobuf::uint32 value) {
  set_has_quality();
  quality_ = value;
}

// repeated .SlotInfoBean slotInfoBean = 4;
inline int EquipmentInfoBean::slotinfobean_size() const {
  return slotinfobean_.size();
}
inline void EquipmentInfoBean::clear_slotinfobean() {
  slotinfobean_.Clear();
}
inline const ::SlotInfoBean& EquipmentInfoBean::slotinfobean(int index) const {
  return slotinfobean_.Get(index);
}
inline ::SlotInfoBean* EquipmentInfoBean::mutable_slotinfobean(int index) {
  return slotinfobean_.Mutable(index);
}
inline ::SlotInfoBean* EquipmentInfoBean::add_slotinfobean() {
  return slotinfobean_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SlotInfoBean >&
EquipmentInfoBean::slotinfobean() const {
  return slotinfobean_;
}
inline ::google::protobuf::RepeatedPtrField< ::SlotInfoBean >*
EquipmentInfoBean::mutable_slotinfobean() {
  return &slotinfobean_;
}

// -------------------------------------------------------------------

// HeroInfoBean

// required uint32 id = 1;
inline bool HeroInfoBean::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroInfoBean::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroInfoBean::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroInfoBean::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 HeroInfoBean::id() const {
  return id_;
}
inline void HeroInfoBean::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required uint32 level = 2;
inline bool HeroInfoBean::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroInfoBean::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroInfoBean::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroInfoBean::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 HeroInfoBean::level() const {
  return level_;
}
inline void HeroInfoBean::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
}

// required uint32 experience = 3;
inline bool HeroInfoBean::has_experience() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HeroInfoBean::set_has_experience() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HeroInfoBean::clear_has_experience() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HeroInfoBean::clear_experience() {
  experience_ = 0u;
  clear_has_experience();
}
inline ::google::protobuf::uint32 HeroInfoBean::experience() const {
  return experience_;
}
inline void HeroInfoBean::set_experience(::google::protobuf::uint32 value) {
  set_has_experience();
  experience_ = value;
}

// required uint32 star = 4;
inline bool HeroInfoBean::has_star() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HeroInfoBean::set_has_star() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HeroInfoBean::clear_has_star() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HeroInfoBean::clear_star() {
  star_ = 0u;
  clear_has_star();
}
inline ::google::protobuf::uint32 HeroInfoBean::star() const {
  return star_;
}
inline void HeroInfoBean::set_star(::google::protobuf::uint32 value) {
  set_has_star();
  star_ = value;
}

// required uint32 quality = 5;
inline bool HeroInfoBean::has_quality() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HeroInfoBean::set_has_quality() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HeroInfoBean::clear_has_quality() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HeroInfoBean::clear_quality() {
  quality_ = 0u;
  clear_has_quality();
}
inline ::google::protobuf::uint32 HeroInfoBean::quality() const {
  return quality_;
}
inline void HeroInfoBean::set_quality(::google::protobuf::uint32 value) {
  set_has_quality();
  quality_ = value;
}

// repeated uint32 currentPatience = 6;
inline int HeroInfoBean::currentpatience_size() const {
  return currentpatience_.size();
}
inline void HeroInfoBean::clear_currentpatience() {
  currentpatience_.Clear();
}
inline ::google::protobuf::uint32 HeroInfoBean::currentpatience(int index) const {
  return currentpatience_.Get(index);
}
inline void HeroInfoBean::set_currentpatience(int index, ::google::protobuf::uint32 value) {
  currentpatience_.Set(index, value);
}
inline void HeroInfoBean::add_currentpatience(::google::protobuf::uint32 value) {
  currentpatience_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
HeroInfoBean::currentpatience() const {
  return currentpatience_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
HeroInfoBean::mutable_currentpatience() {
  return &currentpatience_;
}

// required bool isSave = 7;
inline bool HeroInfoBean::has_issave() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void HeroInfoBean::set_has_issave() {
  _has_bits_[0] |= 0x00000040u;
}
inline void HeroInfoBean::clear_has_issave() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void HeroInfoBean::clear_issave() {
  issave_ = false;
  clear_has_issave();
}
inline bool HeroInfoBean::issave() const {
  return issave_;
}
inline void HeroInfoBean::set_issave(bool value) {
  set_has_issave();
  issave_ = value;
}

// required uint32 trainType = 8;
inline bool HeroInfoBean::has_traintype() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void HeroInfoBean::set_has_traintype() {
  _has_bits_[0] |= 0x00000080u;
}
inline void HeroInfoBean::clear_has_traintype() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void HeroInfoBean::clear_traintype() {
  traintype_ = 0u;
  clear_has_traintype();
}
inline ::google::protobuf::uint32 HeroInfoBean::traintype() const {
  return traintype_;
}
inline void HeroInfoBean::set_traintype(::google::protobuf::uint32 value) {
  set_has_traintype();
  traintype_ = value;
}

// repeated uint32 waitPatience = 9;
inline int HeroInfoBean::waitpatience_size() const {
  return waitpatience_.size();
}
inline void HeroInfoBean::clear_waitpatience() {
  waitpatience_.Clear();
}
inline ::google::protobuf::uint32 HeroInfoBean::waitpatience(int index) const {
  return waitpatience_.Get(index);
}
inline void HeroInfoBean::set_waitpatience(int index, ::google::protobuf::uint32 value) {
  waitpatience_.Set(index, value);
}
inline void HeroInfoBean::add_waitpatience(::google::protobuf::uint32 value) {
  waitpatience_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
HeroInfoBean::waitpatience() const {
  return waitpatience_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
HeroInfoBean::mutable_waitpatience() {
  return &waitpatience_;
}

// repeated .EquipmentInfoBean equipmentInfoBean = 10;
inline int HeroInfoBean::equipmentinfobean_size() const {
  return equipmentinfobean_.size();
}
inline void HeroInfoBean::clear_equipmentinfobean() {
  equipmentinfobean_.Clear();
}
inline const ::EquipmentInfoBean& HeroInfoBean::equipmentinfobean(int index) const {
  return equipmentinfobean_.Get(index);
}
inline ::EquipmentInfoBean* HeroInfoBean::mutable_equipmentinfobean(int index) {
  return equipmentinfobean_.Mutable(index);
}
inline ::EquipmentInfoBean* HeroInfoBean::add_equipmentinfobean() {
  return equipmentinfobean_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::EquipmentInfoBean >&
HeroInfoBean::equipmentinfobean() const {
  return equipmentinfobean_;
}
inline ::google::protobuf::RepeatedPtrField< ::EquipmentInfoBean >*
HeroInfoBean::mutable_equipmentinfobean() {
  return &equipmentinfobean_;
}

// -------------------------------------------------------------------

// ChangeToStoneKeyIdBean

// required uint32 itemKeyId = 1;
inline bool ChangeToStoneKeyIdBean::has_itemkeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeToStoneKeyIdBean::set_has_itemkeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeToStoneKeyIdBean::clear_has_itemkeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeToStoneKeyIdBean::clear_itemkeyid() {
  itemkeyid_ = 0u;
  clear_has_itemkeyid();
}
inline ::google::protobuf::uint32 ChangeToStoneKeyIdBean::itemkeyid() const {
  return itemkeyid_;
}
inline void ChangeToStoneKeyIdBean::set_itemkeyid(::google::protobuf::uint32 value) {
  set_has_itemkeyid();
  itemkeyid_ = value;
}

// required uint32 count = 2;
inline bool ChangeToStoneKeyIdBean::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeToStoneKeyIdBean::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeToStoneKeyIdBean::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeToStoneKeyIdBean::clear_count() {
  count_ = 0u;
  clear_has_count();
}
inline ::google::protobuf::uint32 ChangeToStoneKeyIdBean::count() const {
  return count_;
}
inline void ChangeToStoneKeyIdBean::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
}

// -------------------------------------------------------------------

// GetHeroInfoUp

// required string userId = 1;
inline bool GetHeroInfoUp::has_userid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetHeroInfoUp::set_has_userid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetHeroInfoUp::clear_has_userid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetHeroInfoUp::clear_userid() {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    userid_->clear();
  }
  clear_has_userid();
}
inline const ::std::string& GetHeroInfoUp::userid() const {
  return *userid_;
}
inline void GetHeroInfoUp::set_userid(const ::std::string& value) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(value);
}
inline void GetHeroInfoUp::set_userid(const char* value) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(value);
}
inline void GetHeroInfoUp::set_userid(const char* value, size_t size) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetHeroInfoUp::mutable_userid() {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  return userid_;
}
inline ::std::string* GetHeroInfoUp::release_userid() {
  clear_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = userid_;
    userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GetHeroInfoUp::set_allocated_userid(::std::string* userid) {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    delete userid_;
  }
  if (userid) {
    set_has_userid();
    userid_ = userid;
  } else {
    clear_has_userid();
    userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// GetHeroInfoDown

// required string userId = 1;
inline bool GetHeroInfoDown::has_userid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetHeroInfoDown::set_has_userid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetHeroInfoDown::clear_has_userid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetHeroInfoDown::clear_userid() {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    userid_->clear();
  }
  clear_has_userid();
}
inline const ::std::string& GetHeroInfoDown::userid() const {
  return *userid_;
}
inline void GetHeroInfoDown::set_userid(const ::std::string& value) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(value);
}
inline void GetHeroInfoDown::set_userid(const char* value) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(value);
}
inline void GetHeroInfoDown::set_userid(const char* value, size_t size) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetHeroInfoDown::mutable_userid() {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  return userid_;
}
inline ::std::string* GetHeroInfoDown::release_userid() {
  clear_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = userid_;
    userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GetHeroInfoDown::set_allocated_userid(::std::string* userid) {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    delete userid_;
  }
  if (userid) {
    set_has_userid();
    userid_ = userid;
  } else {
    clear_has_userid();
    userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 heroExp = 2;
inline bool GetHeroInfoDown::has_heroexp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetHeroInfoDown::set_has_heroexp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetHeroInfoDown::clear_has_heroexp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetHeroInfoDown::clear_heroexp() {
  heroexp_ = 0u;
  clear_has_heroexp();
}
inline ::google::protobuf::uint32 GetHeroInfoDown::heroexp() const {
  return heroexp_;
}
inline void GetHeroInfoDown::set_heroexp(::google::protobuf::uint32 value) {
  set_has_heroexp();
  heroexp_ = value;
}

// repeated .HeroInfoBean heroInfoBean = 3;
inline int GetHeroInfoDown::heroinfobean_size() const {
  return heroinfobean_.size();
}
inline void GetHeroInfoDown::clear_heroinfobean() {
  heroinfobean_.Clear();
}
inline const ::HeroInfoBean& GetHeroInfoDown::heroinfobean(int index) const {
  return heroinfobean_.Get(index);
}
inline ::HeroInfoBean* GetHeroInfoDown::mutable_heroinfobean(int index) {
  return heroinfobean_.Mutable(index);
}
inline ::HeroInfoBean* GetHeroInfoDown::add_heroinfobean() {
  return heroinfobean_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::HeroInfoBean >&
GetHeroInfoDown::heroinfobean() const {
  return heroinfobean_;
}
inline ::google::protobuf::RepeatedPtrField< ::HeroInfoBean >*
GetHeroInfoDown::mutable_heroinfobean() {
  return &heroinfobean_;
}

// -------------------------------------------------------------------

// UseHeroBookUp

// required uint32 itemId = 1;
inline bool UseHeroBookUp::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UseHeroBookUp::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UseHeroBookUp::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UseHeroBookUp::clear_itemid() {
  itemid_ = 0u;
  clear_has_itemid();
}
inline ::google::protobuf::uint32 UseHeroBookUp::itemid() const {
  return itemid_;
}
inline void UseHeroBookUp::set_itemid(::google::protobuf::uint32 value) {
  set_has_itemid();
  itemid_ = value;
}

// -------------------------------------------------------------------

// UseHeroBookDown

// required bool isHaveHero = 1;
inline bool UseHeroBookDown::has_ishavehero() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UseHeroBookDown::set_has_ishavehero() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UseHeroBookDown::clear_has_ishavehero() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UseHeroBookDown::clear_ishavehero() {
  ishavehero_ = false;
  clear_has_ishavehero();
}
inline bool UseHeroBookDown::ishavehero() const {
  return ishavehero_;
}
inline void UseHeroBookDown::set_ishavehero(bool value) {
  set_has_ishavehero();
  ishavehero_ = value;
}

// required uint32 heroKeyId = 2;
inline bool UseHeroBookDown::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UseHeroBookDown::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UseHeroBookDown::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UseHeroBookDown::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 UseHeroBookDown::herokeyid() const {
  return herokeyid_;
}
inline void UseHeroBookDown::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}

// optional .ChangeToStoneKeyIdBean changeToStoneKeyIdBean = 3;
inline bool UseHeroBookDown::has_changetostonekeyidbean() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UseHeroBookDown::set_has_changetostonekeyidbean() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UseHeroBookDown::clear_has_changetostonekeyidbean() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UseHeroBookDown::clear_changetostonekeyidbean() {
  if (changetostonekeyidbean_ != NULL) changetostonekeyidbean_->::ChangeToStoneKeyIdBean::Clear();
  clear_has_changetostonekeyidbean();
}
inline const ::ChangeToStoneKeyIdBean& UseHeroBookDown::changetostonekeyidbean() const {
  return changetostonekeyidbean_ != NULL ? *changetostonekeyidbean_ : *default_instance_->changetostonekeyidbean_;
}
inline ::ChangeToStoneKeyIdBean* UseHeroBookDown::mutable_changetostonekeyidbean() {
  set_has_changetostonekeyidbean();
  if (changetostonekeyidbean_ == NULL) changetostonekeyidbean_ = new ::ChangeToStoneKeyIdBean;
  return changetostonekeyidbean_;
}
inline ::ChangeToStoneKeyIdBean* UseHeroBookDown::release_changetostonekeyidbean() {
  clear_has_changetostonekeyidbean();
  ::ChangeToStoneKeyIdBean* temp = changetostonekeyidbean_;
  changetostonekeyidbean_ = NULL;
  return temp;
}
inline void UseHeroBookDown::set_allocated_changetostonekeyidbean(::ChangeToStoneKeyIdBean* changetostonekeyidbean) {
  delete changetostonekeyidbean_;
  changetostonekeyidbean_ = changetostonekeyidbean;
  if (changetostonekeyidbean) {
    set_has_changetostonekeyidbean();
  } else {
    clear_has_changetostonekeyidbean();
  }
}

// -------------------------------------------------------------------

// CallHeroUp

// required uint32 heroKeyId = 1;
inline bool CallHeroUp::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CallHeroUp::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CallHeroUp::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CallHeroUp::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 CallHeroUp::herokeyid() const {
  return herokeyid_;
}
inline void CallHeroUp::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}

// -------------------------------------------------------------------

// HeroEvolutionUp

// required uint32 heroKeyId = 1;
inline bool HeroEvolutionUp::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroEvolutionUp::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroEvolutionUp::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroEvolutionUp::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 HeroEvolutionUp::herokeyid() const {
  return herokeyid_;
}
inline void HeroEvolutionUp::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}

// -------------------------------------------------------------------

// HeroTrainUp

// required uint32 heroKeyId = 1;
inline bool HeroTrainUp::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroTrainUp::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroTrainUp::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroTrainUp::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 HeroTrainUp::herokeyid() const {
  return herokeyid_;
}
inline void HeroTrainUp::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}

// required uint32 trainType = 2;
inline bool HeroTrainUp::has_traintype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroTrainUp::set_has_traintype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroTrainUp::clear_has_traintype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroTrainUp::clear_traintype() {
  traintype_ = 0u;
  clear_has_traintype();
}
inline ::google::protobuf::uint32 HeroTrainUp::traintype() const {
  return traintype_;
}
inline void HeroTrainUp::set_traintype(::google::protobuf::uint32 value) {
  set_has_traintype();
  traintype_ = value;
}

// -------------------------------------------------------------------

// HeroTrainDown

// required uint32 heroKeyId = 1;
inline bool HeroTrainDown::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroTrainDown::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroTrainDown::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroTrainDown::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 HeroTrainDown::herokeyid() const {
  return herokeyid_;
}
inline void HeroTrainDown::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}

// repeated uint32 patiences = 2;
inline int HeroTrainDown::patiences_size() const {
  return patiences_.size();
}
inline void HeroTrainDown::clear_patiences() {
  patiences_.Clear();
}
inline ::google::protobuf::uint32 HeroTrainDown::patiences(int index) const {
  return patiences_.Get(index);
}
inline void HeroTrainDown::set_patiences(int index, ::google::protobuf::uint32 value) {
  patiences_.Set(index, value);
}
inline void HeroTrainDown::add_patiences(::google::protobuf::uint32 value) {
  patiences_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
HeroTrainDown::patiences() const {
  return patiences_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
HeroTrainDown::mutable_patiences() {
  return &patiences_;
}

// -------------------------------------------------------------------

// SaveTrainPatienceUp

// required uint32 heroKeyId = 1;
inline bool SaveTrainPatienceUp::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SaveTrainPatienceUp::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SaveTrainPatienceUp::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SaveTrainPatienceUp::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 SaveTrainPatienceUp::herokeyid() const {
  return herokeyid_;
}
inline void SaveTrainPatienceUp::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}

// -------------------------------------------------------------------

// CancelTrainPatienceUp

// required uint32 heroKeyId = 1;
inline bool CancelTrainPatienceUp::has_herokeyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CancelTrainPatienceUp::set_has_herokeyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CancelTrainPatienceUp::clear_has_herokeyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CancelTrainPatienceUp::clear_herokeyid() {
  herokeyid_ = 0u;
  clear_has_herokeyid();
}
inline ::google::protobuf::uint32 CancelTrainPatienceUp::herokeyid() const {
  return herokeyid_;
}
inline void CancelTrainPatienceUp::set_herokeyid(::google::protobuf::uint32 value) {
  set_has_herokeyid();
  herokeyid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::HeroCommondIdEnum>() {
  return ::HeroCommondIdEnum_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_1100300_5fHeroMessage_2eproto__INCLUDED
