// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1999000_LErrorMessage.proto

package com.cwa.message;

public final class LErrorMessage {
  private LErrorMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code LErrorCommondIdEnum}
   *
   * <pre>
   *指令号枚举
   * </pre>
   */
  public enum LErrorCommondIdEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>_LErrorDown = 1999001;</code>
     */
    _LErrorDown(0, 1999001),
    ;

    /**
     * <code>_LErrorDown = 1999001;</code>
     */
    public static final int _LErrorDown_VALUE = 1999001;


    public final int getNumber() { return value; }

    public static LErrorCommondIdEnum valueOf(int value) {
      switch (value) {
        case 1999001: return _LErrorDown;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LErrorCommondIdEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LErrorCommondIdEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LErrorCommondIdEnum>() {
            public LErrorCommondIdEnum findValueByNumber(int number) {
              return LErrorCommondIdEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cwa.message.LErrorMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final LErrorCommondIdEnum[] VALUES = values();

    public static LErrorCommondIdEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LErrorCommondIdEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LErrorCommondIdEnum)
  }

  /**
   * Protobuf enum {@code LErrorTypeEnum}
   *
   * <pre>
   *逻辑错误类型
   * </pre>
   */
  public enum LErrorTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>InputError = 1;</code>
     *
     * <pre>
     *输入错误，这里的错误可能会很细
     * </pre>
     */
    InputError(0, 1),
    /**
     * <code>DataError = 2;</code>
     *
     * <pre>
     *数据错误，这个错误客户端重新获取模块数据
     * </pre>
     */
    DataError(1, 2),
    /**
     * <code>SystemError = 3;</code>
     *
     * <pre>
     *系统错误，暂时就模块服务器不可用
     * </pre>
     */
    SystemError(2, 3),
    ;

    /**
     * <code>InputError = 1;</code>
     *
     * <pre>
     *输入错误，这里的错误可能会很细
     * </pre>
     */
    public static final int InputError_VALUE = 1;
    /**
     * <code>DataError = 2;</code>
     *
     * <pre>
     *数据错误，这个错误客户端重新获取模块数据
     * </pre>
     */
    public static final int DataError_VALUE = 2;
    /**
     * <code>SystemError = 3;</code>
     *
     * <pre>
     *系统错误，暂时就模块服务器不可用
     * </pre>
     */
    public static final int SystemError_VALUE = 3;


    public final int getNumber() { return value; }

    public static LErrorTypeEnum valueOf(int value) {
      switch (value) {
        case 1: return InputError;
        case 2: return DataError;
        case 3: return SystemError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LErrorTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LErrorTypeEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LErrorTypeEnum>() {
            public LErrorTypeEnum findValueByNumber(int number) {
              return LErrorTypeEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cwa.message.LErrorMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final LErrorTypeEnum[] VALUES = values();

    public static LErrorTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LErrorTypeEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LErrorTypeEnum)
  }

  /**
   * Protobuf enum {@code ModuleTypeEnum}
   *
   * <pre>
   *模块枚举
   * </pre>
   */
  public enum ModuleTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MT_User = 0;</code>
     *
     * <pre>
     *用户
     * </pre>
     */
    MT_User(0, 0),
    /**
     * <code>MT_Item = 1;</code>
     *
     * <pre>
     *道具
     * </pre>
     */
    MT_Item(1, 1),
    /**
     * <code>MT_Room = 2;</code>
     *
     * <pre>
     *房间
     * </pre>
     */
    MT_Room(2, 2),
    /**
     * <code>MT_Hero = 3;</code>
     *
     * <pre>
     *英雄
     * </pre>
     */
    MT_Hero(3, 3),
    /**
     * <code>MT_Economy = 4;</code>
     *
     * <pre>
     *经济
     * </pre>
     */
    MT_Economy(4, 4),
    /**
     * <code>MT_Equipment = 5;</code>
     *
     * <pre>
     *装备
     * </pre>
     */
    MT_Equipment(5, 5),
    /**
     * <code>MT_Formation = 6;</code>
     *
     * <pre>
     *队伍
     * </pre>
     */
    MT_Formation(6, 6),
    /**
     * <code>MT_Vip = 7;</code>
     *
     * <pre>
     *vip
     * </pre>
     */
    MT_Vip(7, 7),
    /**
     * <code>MT_Match = 8;</code>
     *
     * <pre>
     *副本
     * </pre>
     */
    MT_Match(8, 8),
    ;

    /**
     * <code>MT_User = 0;</code>
     *
     * <pre>
     *用户
     * </pre>
     */
    public static final int MT_User_VALUE = 0;
    /**
     * <code>MT_Item = 1;</code>
     *
     * <pre>
     *道具
     * </pre>
     */
    public static final int MT_Item_VALUE = 1;
    /**
     * <code>MT_Room = 2;</code>
     *
     * <pre>
     *房间
     * </pre>
     */
    public static final int MT_Room_VALUE = 2;
    /**
     * <code>MT_Hero = 3;</code>
     *
     * <pre>
     *英雄
     * </pre>
     */
    public static final int MT_Hero_VALUE = 3;
    /**
     * <code>MT_Economy = 4;</code>
     *
     * <pre>
     *经济
     * </pre>
     */
    public static final int MT_Economy_VALUE = 4;
    /**
     * <code>MT_Equipment = 5;</code>
     *
     * <pre>
     *装备
     * </pre>
     */
    public static final int MT_Equipment_VALUE = 5;
    /**
     * <code>MT_Formation = 6;</code>
     *
     * <pre>
     *队伍
     * </pre>
     */
    public static final int MT_Formation_VALUE = 6;
    /**
     * <code>MT_Vip = 7;</code>
     *
     * <pre>
     *vip
     * </pre>
     */
    public static final int MT_Vip_VALUE = 7;
    /**
     * <code>MT_Match = 8;</code>
     *
     * <pre>
     *副本
     * </pre>
     */
    public static final int MT_Match_VALUE = 8;


    public final int getNumber() { return value; }

    public static ModuleTypeEnum valueOf(int value) {
      switch (value) {
        case 0: return MT_User;
        case 1: return MT_Item;
        case 2: return MT_Room;
        case 3: return MT_Hero;
        case 4: return MT_Economy;
        case 5: return MT_Equipment;
        case 6: return MT_Formation;
        case 7: return MT_Vip;
        case 8: return MT_Match;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ModuleTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModuleTypeEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModuleTypeEnum>() {
            public ModuleTypeEnum findValueByNumber(int number) {
              return ModuleTypeEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cwa.message.LErrorMessage.getDescriptor().getEnumTypes().get(2);
    }

    private static final ModuleTypeEnum[] VALUES = values();

    public static ModuleTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ModuleTypeEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ModuleTypeEnum)
  }

  /**
   * Protobuf enum {@code InputErrorTypeEnum}
   *
   * <pre>
   *输入错误类型，玩家主动输入或不是从数据中取的值（可能客户端代码写错了）都认为是输入的错误为
   * </pre>
   */
  public enum InputErrorTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IE_UserName = 1;</code>
     *
     * <pre>
     *名字输入错误
     * </pre>
     */
    IE_UserName(0, 1),
    /**
     * <code>IE_ConsumeType = 2;</code>
     *
     * <pre>
     *消费类型错误
     * </pre>
     */
    IE_ConsumeType(1, 2),
    /**
     * <code>IE_FormationType = 3;</code>
     *
     * <pre>
     *阵容类型错误
     * </pre>
     */
    IE_FormationType(2, 3),
    /**
     * <code>IE_IconType = 4;</code>
     *
     * <pre>
     *头像类型错误
     * </pre>
     */
    IE_IconType(3, 4),
    /**
     * <code>IE_MatchType = 5;</code>
     *
     * <pre>
     *副本类型错误
     * </pre>
     */
    IE_MatchType(4, 5),
    /**
     * <code>IE_PasscardId = 6;</code>
     *
     * <pre>
     *关卡id错误
     * </pre>
     */
    IE_PasscardId(5, 6),
    ;

    /**
     * <code>IE_Star = 6;</code>
     *
     * <pre>
     *星级错误
     * </pre>
     */
    public static final InputErrorTypeEnum IE_Star = IE_PasscardId;
    /**
     * <code>IE_UserName = 1;</code>
     *
     * <pre>
     *名字输入错误
     * </pre>
     */
    public static final int IE_UserName_VALUE = 1;
    /**
     * <code>IE_ConsumeType = 2;</code>
     *
     * <pre>
     *消费类型错误
     * </pre>
     */
    public static final int IE_ConsumeType_VALUE = 2;
    /**
     * <code>IE_FormationType = 3;</code>
     *
     * <pre>
     *阵容类型错误
     * </pre>
     */
    public static final int IE_FormationType_VALUE = 3;
    /**
     * <code>IE_IconType = 4;</code>
     *
     * <pre>
     *头像类型错误
     * </pre>
     */
    public static final int IE_IconType_VALUE = 4;
    /**
     * <code>IE_MatchType = 5;</code>
     *
     * <pre>
     *副本类型错误
     * </pre>
     */
    public static final int IE_MatchType_VALUE = 5;
    /**
     * <code>IE_PasscardId = 6;</code>
     *
     * <pre>
     *关卡id错误
     * </pre>
     */
    public static final int IE_PasscardId_VALUE = 6;
    /**
     * <code>IE_Star = 6;</code>
     *
     * <pre>
     *星级错误
     * </pre>
     */
    public static final int IE_Star_VALUE = 6;


    public final int getNumber() { return value; }

    public static InputErrorTypeEnum valueOf(int value) {
      switch (value) {
        case 1: return IE_UserName;
        case 2: return IE_ConsumeType;
        case 3: return IE_FormationType;
        case 4: return IE_IconType;
        case 5: return IE_MatchType;
        case 6: return IE_PasscardId;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InputErrorTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<InputErrorTypeEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InputErrorTypeEnum>() {
            public InputErrorTypeEnum findValueByNumber(int number) {
              return InputErrorTypeEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cwa.message.LErrorMessage.getDescriptor().getEnumTypes().get(3);
    }

    private static final InputErrorTypeEnum[] VALUES = {
      IE_UserName, IE_ConsumeType, IE_FormationType, IE_IconType, IE_MatchType, IE_PasscardId, IE_Star, 
    };

    public static InputErrorTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private InputErrorTypeEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InputErrorTypeEnum)
  }

  public interface LErrorDownOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string errorMessage = 1;
    /**
     * <code>required string errorMessage = 1;</code>
     *
     * <pre>
     *错误消息名
     * </pre>
     */
    boolean hasErrorMessage();
    /**
     * <code>required string errorMessage = 1;</code>
     *
     * <pre>
     *错误消息名
     * </pre>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>required string errorMessage = 1;</code>
     *
     * <pre>
     *错误消息名
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    // required .LErrorTypeEnum errorType = 2;
    /**
     * <code>required .LErrorTypeEnum errorType = 2;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    boolean hasErrorType();
    /**
     * <code>required .LErrorTypeEnum errorType = 2;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    com.cwa.message.LErrorMessage.LErrorTypeEnum getErrorType();

    // optional .ModuleTypeEnum moduleType = 3;
    /**
     * <code>optional .ModuleTypeEnum moduleType = 3;</code>
     *
     * <pre>
     *模块枚举，2和3类型公用
     * </pre>
     */
    boolean hasModuleType();
    /**
     * <code>optional .ModuleTypeEnum moduleType = 3;</code>
     *
     * <pre>
     *模块枚举，2和3类型公用
     * </pre>
     */
    com.cwa.message.LErrorMessage.ModuleTypeEnum getModuleType();

    // optional .InputErrorTypeEnum inputErrorType = 4;
    /**
     * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
     *
     * <pre>
     *输入错误类型
     * </pre>
     */
    boolean hasInputErrorType();
    /**
     * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
     *
     * <pre>
     *输入错误类型
     * </pre>
     */
    com.cwa.message.LErrorMessage.InputErrorTypeEnum getInputErrorType();
  }
  /**
   * Protobuf type {@code LErrorDown}
   *
   * <pre>
   *1999001_错误消息发送
   * </pre>
   */
  public static final class LErrorDown extends
      com.google.protobuf.GeneratedMessage
      implements LErrorDownOrBuilder {
    // Use LErrorDown.newBuilder() to construct.
    private LErrorDown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LErrorDown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LErrorDown defaultInstance;
    public static LErrorDown getDefaultInstance() {
      return defaultInstance;
    }

    public LErrorDown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LErrorDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              errorMessage_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.cwa.message.LErrorMessage.LErrorTypeEnum value = com.cwa.message.LErrorMessage.LErrorTypeEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                errorType_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.cwa.message.LErrorMessage.ModuleTypeEnum value = com.cwa.message.LErrorMessage.ModuleTypeEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                moduleType_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.cwa.message.LErrorMessage.InputErrorTypeEnum value = com.cwa.message.LErrorMessage.InputErrorTypeEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                inputErrorType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cwa.message.LErrorMessage.internal_static_LErrorDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cwa.message.LErrorMessage.internal_static_LErrorDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cwa.message.LErrorMessage.LErrorDown.class, com.cwa.message.LErrorMessage.LErrorDown.Builder.class);
    }

    public static com.google.protobuf.Parser<LErrorDown> PARSER =
        new com.google.protobuf.AbstractParser<LErrorDown>() {
      public LErrorDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LErrorDown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LErrorDown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string errorMessage = 1;
    public static final int ERRORMESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object errorMessage_;
    /**
     * <code>required string errorMessage = 1;</code>
     *
     * <pre>
     *错误消息名
     * </pre>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string errorMessage = 1;</code>
     *
     * <pre>
     *错误消息名
     * </pre>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string errorMessage = 1;</code>
     *
     * <pre>
     *错误消息名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .LErrorTypeEnum errorType = 2;
    public static final int ERRORTYPE_FIELD_NUMBER = 2;
    private com.cwa.message.LErrorMessage.LErrorTypeEnum errorType_;
    /**
     * <code>required .LErrorTypeEnum errorType = 2;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    public boolean hasErrorType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .LErrorTypeEnum errorType = 2;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    public com.cwa.message.LErrorMessage.LErrorTypeEnum getErrorType() {
      return errorType_;
    }

    // optional .ModuleTypeEnum moduleType = 3;
    public static final int MODULETYPE_FIELD_NUMBER = 3;
    private com.cwa.message.LErrorMessage.ModuleTypeEnum moduleType_;
    /**
     * <code>optional .ModuleTypeEnum moduleType = 3;</code>
     *
     * <pre>
     *模块枚举，2和3类型公用
     * </pre>
     */
    public boolean hasModuleType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ModuleTypeEnum moduleType = 3;</code>
     *
     * <pre>
     *模块枚举，2和3类型公用
     * </pre>
     */
    public com.cwa.message.LErrorMessage.ModuleTypeEnum getModuleType() {
      return moduleType_;
    }

    // optional .InputErrorTypeEnum inputErrorType = 4;
    public static final int INPUTERRORTYPE_FIELD_NUMBER = 4;
    private com.cwa.message.LErrorMessage.InputErrorTypeEnum inputErrorType_;
    /**
     * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
     *
     * <pre>
     *输入错误类型
     * </pre>
     */
    public boolean hasInputErrorType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
     *
     * <pre>
     *输入错误类型
     * </pre>
     */
    public com.cwa.message.LErrorMessage.InputErrorTypeEnum getInputErrorType() {
      return inputErrorType_;
    }

    private void initFields() {
      errorMessage_ = "";
      errorType_ = com.cwa.message.LErrorMessage.LErrorTypeEnum.InputError;
      moduleType_ = com.cwa.message.LErrorMessage.ModuleTypeEnum.MT_User;
      inputErrorType_ = com.cwa.message.LErrorMessage.InputErrorTypeEnum.IE_UserName;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrorMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, errorType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, moduleType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, inputErrorType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errorType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, moduleType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, inputErrorType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.LErrorMessage.LErrorDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cwa.message.LErrorMessage.LErrorDown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LErrorDown}
     *
     * <pre>
     *1999001_错误消息发送
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cwa.message.LErrorMessage.LErrorDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cwa.message.LErrorMessage.internal_static_LErrorDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cwa.message.LErrorMessage.internal_static_LErrorDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cwa.message.LErrorMessage.LErrorDown.class, com.cwa.message.LErrorMessage.LErrorDown.Builder.class);
      }

      // Construct using com.cwa.message.LErrorMessage.LErrorDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        errorType_ = com.cwa.message.LErrorMessage.LErrorTypeEnum.InputError;
        bitField0_ = (bitField0_ & ~0x00000002);
        moduleType_ = com.cwa.message.LErrorMessage.ModuleTypeEnum.MT_User;
        bitField0_ = (bitField0_ & ~0x00000004);
        inputErrorType_ = com.cwa.message.LErrorMessage.InputErrorTypeEnum.IE_UserName;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cwa.message.LErrorMessage.internal_static_LErrorDown_descriptor;
      }

      public com.cwa.message.LErrorMessage.LErrorDown getDefaultInstanceForType() {
        return com.cwa.message.LErrorMessage.LErrorDown.getDefaultInstance();
      }

      public com.cwa.message.LErrorMessage.LErrorDown build() {
        com.cwa.message.LErrorMessage.LErrorDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cwa.message.LErrorMessage.LErrorDown buildPartial() {
        com.cwa.message.LErrorMessage.LErrorDown result = new com.cwa.message.LErrorMessage.LErrorDown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorType_ = errorType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.moduleType_ = moduleType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.inputErrorType_ = inputErrorType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cwa.message.LErrorMessage.LErrorDown) {
          return mergeFrom((com.cwa.message.LErrorMessage.LErrorDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cwa.message.LErrorMessage.LErrorDown other) {
        if (other == com.cwa.message.LErrorMessage.LErrorDown.getDefaultInstance()) return this;
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000001;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.hasErrorType()) {
          setErrorType(other.getErrorType());
        }
        if (other.hasModuleType()) {
          setModuleType(other.getModuleType());
        }
        if (other.hasInputErrorType()) {
          setInputErrorType(other.getInputErrorType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorMessage()) {
          
          return false;
        }
        if (!hasErrorType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cwa.message.LErrorMessage.LErrorDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cwa.message.LErrorMessage.LErrorDown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string errorMessage = 1;
      private java.lang.Object errorMessage_ = "";
      /**
       * <code>required string errorMessage = 1;</code>
       *
       * <pre>
       *错误消息名
       * </pre>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string errorMessage = 1;</code>
       *
       * <pre>
       *错误消息名
       * </pre>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string errorMessage = 1;</code>
       *
       * <pre>
       *错误消息名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string errorMessage = 1;</code>
       *
       * <pre>
       *错误消息名
       * </pre>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string errorMessage = 1;</code>
       *
       * <pre>
       *错误消息名
       * </pre>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string errorMessage = 1;</code>
       *
       * <pre>
       *错误消息名
       * </pre>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      // required .LErrorTypeEnum errorType = 2;
      private com.cwa.message.LErrorMessage.LErrorTypeEnum errorType_ = com.cwa.message.LErrorMessage.LErrorTypeEnum.InputError;
      /**
       * <code>required .LErrorTypeEnum errorType = 2;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public boolean hasErrorType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .LErrorTypeEnum errorType = 2;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public com.cwa.message.LErrorMessage.LErrorTypeEnum getErrorType() {
        return errorType_;
      }
      /**
       * <code>required .LErrorTypeEnum errorType = 2;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public Builder setErrorType(com.cwa.message.LErrorMessage.LErrorTypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        errorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .LErrorTypeEnum errorType = 2;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public Builder clearErrorType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorType_ = com.cwa.message.LErrorMessage.LErrorTypeEnum.InputError;
        onChanged();
        return this;
      }

      // optional .ModuleTypeEnum moduleType = 3;
      private com.cwa.message.LErrorMessage.ModuleTypeEnum moduleType_ = com.cwa.message.LErrorMessage.ModuleTypeEnum.MT_User;
      /**
       * <code>optional .ModuleTypeEnum moduleType = 3;</code>
       *
       * <pre>
       *模块枚举，2和3类型公用
       * </pre>
       */
      public boolean hasModuleType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ModuleTypeEnum moduleType = 3;</code>
       *
       * <pre>
       *模块枚举，2和3类型公用
       * </pre>
       */
      public com.cwa.message.LErrorMessage.ModuleTypeEnum getModuleType() {
        return moduleType_;
      }
      /**
       * <code>optional .ModuleTypeEnum moduleType = 3;</code>
       *
       * <pre>
       *模块枚举，2和3类型公用
       * </pre>
       */
      public Builder setModuleType(com.cwa.message.LErrorMessage.ModuleTypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        moduleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ModuleTypeEnum moduleType = 3;</code>
       *
       * <pre>
       *模块枚举，2和3类型公用
       * </pre>
       */
      public Builder clearModuleType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        moduleType_ = com.cwa.message.LErrorMessage.ModuleTypeEnum.MT_User;
        onChanged();
        return this;
      }

      // optional .InputErrorTypeEnum inputErrorType = 4;
      private com.cwa.message.LErrorMessage.InputErrorTypeEnum inputErrorType_ = com.cwa.message.LErrorMessage.InputErrorTypeEnum.IE_UserName;
      /**
       * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
       *
       * <pre>
       *输入错误类型
       * </pre>
       */
      public boolean hasInputErrorType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
       *
       * <pre>
       *输入错误类型
       * </pre>
       */
      public com.cwa.message.LErrorMessage.InputErrorTypeEnum getInputErrorType() {
        return inputErrorType_;
      }
      /**
       * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
       *
       * <pre>
       *输入错误类型
       * </pre>
       */
      public Builder setInputErrorType(com.cwa.message.LErrorMessage.InputErrorTypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        inputErrorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .InputErrorTypeEnum inputErrorType = 4;</code>
       *
       * <pre>
       *输入错误类型
       * </pre>
       */
      public Builder clearInputErrorType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        inputErrorType_ = com.cwa.message.LErrorMessage.InputErrorTypeEnum.IE_UserName;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LErrorDown)
    }

    static {
      defaultInstance = new LErrorDown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LErrorDown)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LErrorDown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LErrorDown_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0331999000_LErrorMessage.proto\"\230\001\n\nLError" +
      "Down\022\024\n\014errorMessage\030\001 \002(\t\022\"\n\terrorType\030" +
      "\002 \002(\0162\017.LErrorTypeEnum\022#\n\nmoduleType\030\003 \001" +
      "(\0162\017.ModuleTypeEnum\022+\n\016inputErrorType\030\004 " +
      "\001(\0162\023.InputErrorTypeEnum*(\n\023LErrorCommon" +
      "dIdEnum\022\021\n\013_LErrorDown\020\231\201z*@\n\016LErrorType" +
      "Enum\022\016\n\nInputError\020\001\022\r\n\tDataError\020\002\022\017\n\013S" +
      "ystemError\020\003*\222\001\n\016ModuleTypeEnum\022\013\n\007MT_Us" +
      "er\020\000\022\013\n\007MT_Item\020\001\022\013\n\007MT_Room\020\002\022\013\n\007MT_Her" +
      "o\020\003\022\016\n\nMT_Economy\020\004\022\020\n\014MT_Equipment\020\005\022\020\n",
      "\014MT_Formation\020\006\022\n\n\006MT_Vip\020\007\022\014\n\010MT_Match\020" +
      "\010*\222\001\n\022InputErrorTypeEnum\022\017\n\013IE_UserName\020" +
      "\001\022\022\n\016IE_ConsumeType\020\002\022\024\n\020IE_FormationTyp" +
      "e\020\003\022\017\n\013IE_IconType\020\004\022\020\n\014IE_MatchType\020\005\022\021" +
      "\n\rIE_PasscardId\020\006\022\013\n\007IE_Star\020\006B \n\017com.cw" +
      "a.messageB\rLErrorMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LErrorDown_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LErrorDown_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LErrorDown_descriptor,
              new java.lang.String[] { "ErrorMessage", "ErrorType", "ModuleType", "InputErrorType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
