// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2100000_PlayerMessage.proto

package com.cwa.message;

public final class PlayerMessage {
  private PlayerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code PlayerCommondIdEnum}
   *
   * <pre>
   *指令号枚举
   * </pre>
   */
  public enum PlayerCommondIdEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>_PlayerLoginUp = 2100001;</code>
     */
    _PlayerLoginUp(0, 2100001),
    /**
     * <code>_PlayerLoginDown = 2100002;</code>
     */
    _PlayerLoginDown(1, 2100002),
    /**
     * <code>_PlayerLogoutUp = 2100003;</code>
     */
    _PlayerLogoutUp(2, 2100003),
    ;

    /**
     * <code>_PlayerLoginUp = 2100001;</code>
     */
    public static final int _PlayerLoginUp_VALUE = 2100001;
    /**
     * <code>_PlayerLoginDown = 2100002;</code>
     */
    public static final int _PlayerLoginDown_VALUE = 2100002;
    /**
     * <code>_PlayerLogoutUp = 2100003;</code>
     */
    public static final int _PlayerLogoutUp_VALUE = 2100003;


    public final int getNumber() { return value; }

    public static PlayerCommondIdEnum valueOf(int value) {
      switch (value) {
        case 2100001: return _PlayerLoginUp;
        case 2100002: return _PlayerLoginDown;
        case 2100003: return _PlayerLogoutUp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlayerCommondIdEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PlayerCommondIdEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlayerCommondIdEnum>() {
            public PlayerCommondIdEnum findValueByNumber(int number) {
              return PlayerCommondIdEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cwa.message.PlayerMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlayerCommondIdEnum[] VALUES = values();

    public static PlayerCommondIdEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PlayerCommondIdEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PlayerCommondIdEnum)
  }

  public interface PlayerLoginUpOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 userId = 1;
    /**
     * <code>required uint64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required uint64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    long getUserId();

    // required uint64 createTime = 2;
    /**
     * <code>required uint64 createTime = 2;</code>
     *
     * <pre>
     *注册时间
     * </pre>
     */
    boolean hasCreateTime();
    /**
     * <code>required uint64 createTime = 2;</code>
     *
     * <pre>
     *注册时间
     * </pre>
     */
    long getCreateTime();
  }
  /**
   * Protobuf type {@code PlayerLoginUp}
   *
   * <pre>
   *2100001_角色登录
   * </pre>
   */
  public static final class PlayerLoginUp extends
      com.google.protobuf.GeneratedMessage
      implements PlayerLoginUpOrBuilder {
    // Use PlayerLoginUp.newBuilder() to construct.
    private PlayerLoginUp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerLoginUp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerLoginUp defaultInstance;
    public static PlayerLoginUp getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerLoginUp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLoginUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cwa.message.PlayerMessage.internal_static_PlayerLoginUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cwa.message.PlayerMessage.internal_static_PlayerLoginUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cwa.message.PlayerMessage.PlayerLoginUp.class, com.cwa.message.PlayerMessage.PlayerLoginUp.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerLoginUp> PARSER =
        new com.google.protobuf.AbstractParser<PlayerLoginUp>() {
      public PlayerLoginUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLoginUp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLoginUp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required uint64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public long getUserId() {
      return userId_;
    }

    // required uint64 createTime = 2;
    public static final int CREATETIME_FIELD_NUMBER = 2;
    private long createTime_;
    /**
     * <code>required uint64 createTime = 2;</code>
     *
     * <pre>
     *注册时间
     * </pre>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 createTime = 2;</code>
     *
     * <pre>
     *注册时间
     * </pre>
     */
    public long getCreateTime() {
      return createTime_;
    }

    private void initFields() {
      userId_ = 0L;
      createTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, createTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, createTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cwa.message.PlayerMessage.PlayerLoginUp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerLoginUp}
     *
     * <pre>
     *2100001_角色登录
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cwa.message.PlayerMessage.PlayerLoginUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLoginUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLoginUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cwa.message.PlayerMessage.PlayerLoginUp.class, com.cwa.message.PlayerMessage.PlayerLoginUp.Builder.class);
      }

      // Construct using com.cwa.message.PlayerMessage.PlayerLoginUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLoginUp_descriptor;
      }

      public com.cwa.message.PlayerMessage.PlayerLoginUp getDefaultInstanceForType() {
        return com.cwa.message.PlayerMessage.PlayerLoginUp.getDefaultInstance();
      }

      public com.cwa.message.PlayerMessage.PlayerLoginUp build() {
        com.cwa.message.PlayerMessage.PlayerLoginUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cwa.message.PlayerMessage.PlayerLoginUp buildPartial() {
        com.cwa.message.PlayerMessage.PlayerLoginUp result = new com.cwa.message.PlayerMessage.PlayerLoginUp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createTime_ = createTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cwa.message.PlayerMessage.PlayerLoginUp) {
          return mergeFrom((com.cwa.message.PlayerMessage.PlayerLoginUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cwa.message.PlayerMessage.PlayerLoginUp other) {
        if (other == com.cwa.message.PlayerMessage.PlayerLoginUp.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasCreateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cwa.message.PlayerMessage.PlayerLoginUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cwa.message.PlayerMessage.PlayerLoginUp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 userId = 1;
      private long userId_ ;
      /**
       * <code>required uint64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required uint64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 createTime = 2;
      private long createTime_ ;
      /**
       * <code>required uint64 createTime = 2;</code>
       *
       * <pre>
       *注册时间
       * </pre>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 createTime = 2;</code>
       *
       * <pre>
       *注册时间
       * </pre>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>required uint64 createTime = 2;</code>
       *
       * <pre>
       *注册时间
       * </pre>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000002;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 createTime = 2;</code>
       *
       * <pre>
       *注册时间
       * </pre>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerLoginUp)
    }

    static {
      defaultInstance = new PlayerLoginUp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerLoginUp)
  }

  public interface PlayerLoginDownOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 loginState = 1;
    /**
     * <code>required uint32 loginState = 1;</code>
     *
     * <pre>
     *登录状态
     * </pre>
     */
    boolean hasLoginState();
    /**
     * <code>required uint32 loginState = 1;</code>
     *
     * <pre>
     *登录状态
     * </pre>
     */
    int getLoginState();

    // required uint64 logoutTime = 2;
    /**
     * <code>required uint64 logoutTime = 2;</code>
     *
     * <pre>
     *上一次下线时间
     * </pre>
     */
    boolean hasLogoutTime();
    /**
     * <code>required uint64 logoutTime = 2;</code>
     *
     * <pre>
     *上一次下线时间
     * </pre>
     */
    long getLogoutTime();
  }
  /**
   * Protobuf type {@code PlayerLoginDown}
   *
   * <pre>
   *2100002_角色登录
   * </pre>
   */
  public static final class PlayerLoginDown extends
      com.google.protobuf.GeneratedMessage
      implements PlayerLoginDownOrBuilder {
    // Use PlayerLoginDown.newBuilder() to construct.
    private PlayerLoginDown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerLoginDown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerLoginDown defaultInstance;
    public static PlayerLoginDown getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerLoginDown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLoginDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loginState_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              logoutTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cwa.message.PlayerMessage.internal_static_PlayerLoginDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cwa.message.PlayerMessage.internal_static_PlayerLoginDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cwa.message.PlayerMessage.PlayerLoginDown.class, com.cwa.message.PlayerMessage.PlayerLoginDown.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerLoginDown> PARSER =
        new com.google.protobuf.AbstractParser<PlayerLoginDown>() {
      public PlayerLoginDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLoginDown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLoginDown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 loginState = 1;
    public static final int LOGINSTATE_FIELD_NUMBER = 1;
    private int loginState_;
    /**
     * <code>required uint32 loginState = 1;</code>
     *
     * <pre>
     *登录状态
     * </pre>
     */
    public boolean hasLoginState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 loginState = 1;</code>
     *
     * <pre>
     *登录状态
     * </pre>
     */
    public int getLoginState() {
      return loginState_;
    }

    // required uint64 logoutTime = 2;
    public static final int LOGOUTTIME_FIELD_NUMBER = 2;
    private long logoutTime_;
    /**
     * <code>required uint64 logoutTime = 2;</code>
     *
     * <pre>
     *上一次下线时间
     * </pre>
     */
    public boolean hasLogoutTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 logoutTime = 2;</code>
     *
     * <pre>
     *上一次下线时间
     * </pre>
     */
    public long getLogoutTime() {
      return logoutTime_;
    }

    private void initFields() {
      loginState_ = 0;
      logoutTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLoginState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogoutTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, loginState_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, logoutTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, loginState_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, logoutTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLoginDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cwa.message.PlayerMessage.PlayerLoginDown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerLoginDown}
     *
     * <pre>
     *2100002_角色登录
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cwa.message.PlayerMessage.PlayerLoginDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLoginDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLoginDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cwa.message.PlayerMessage.PlayerLoginDown.class, com.cwa.message.PlayerMessage.PlayerLoginDown.Builder.class);
      }

      // Construct using com.cwa.message.PlayerMessage.PlayerLoginDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        loginState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        logoutTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLoginDown_descriptor;
      }

      public com.cwa.message.PlayerMessage.PlayerLoginDown getDefaultInstanceForType() {
        return com.cwa.message.PlayerMessage.PlayerLoginDown.getDefaultInstance();
      }

      public com.cwa.message.PlayerMessage.PlayerLoginDown build() {
        com.cwa.message.PlayerMessage.PlayerLoginDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cwa.message.PlayerMessage.PlayerLoginDown buildPartial() {
        com.cwa.message.PlayerMessage.PlayerLoginDown result = new com.cwa.message.PlayerMessage.PlayerLoginDown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginState_ = loginState_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logoutTime_ = logoutTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cwa.message.PlayerMessage.PlayerLoginDown) {
          return mergeFrom((com.cwa.message.PlayerMessage.PlayerLoginDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cwa.message.PlayerMessage.PlayerLoginDown other) {
        if (other == com.cwa.message.PlayerMessage.PlayerLoginDown.getDefaultInstance()) return this;
        if (other.hasLoginState()) {
          setLoginState(other.getLoginState());
        }
        if (other.hasLogoutTime()) {
          setLogoutTime(other.getLogoutTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoginState()) {
          
          return false;
        }
        if (!hasLogoutTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cwa.message.PlayerMessage.PlayerLoginDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cwa.message.PlayerMessage.PlayerLoginDown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 loginState = 1;
      private int loginState_ ;
      /**
       * <code>required uint32 loginState = 1;</code>
       *
       * <pre>
       *登录状态
       * </pre>
       */
      public boolean hasLoginState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 loginState = 1;</code>
       *
       * <pre>
       *登录状态
       * </pre>
       */
      public int getLoginState() {
        return loginState_;
      }
      /**
       * <code>required uint32 loginState = 1;</code>
       *
       * <pre>
       *登录状态
       * </pre>
       */
      public Builder setLoginState(int value) {
        bitField0_ |= 0x00000001;
        loginState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 loginState = 1;</code>
       *
       * <pre>
       *登录状态
       * </pre>
       */
      public Builder clearLoginState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginState_ = 0;
        onChanged();
        return this;
      }

      // required uint64 logoutTime = 2;
      private long logoutTime_ ;
      /**
       * <code>required uint64 logoutTime = 2;</code>
       *
       * <pre>
       *上一次下线时间
       * </pre>
       */
      public boolean hasLogoutTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 logoutTime = 2;</code>
       *
       * <pre>
       *上一次下线时间
       * </pre>
       */
      public long getLogoutTime() {
        return logoutTime_;
      }
      /**
       * <code>required uint64 logoutTime = 2;</code>
       *
       * <pre>
       *上一次下线时间
       * </pre>
       */
      public Builder setLogoutTime(long value) {
        bitField0_ |= 0x00000002;
        logoutTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 logoutTime = 2;</code>
       *
       * <pre>
       *上一次下线时间
       * </pre>
       */
      public Builder clearLogoutTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logoutTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerLoginDown)
    }

    static {
      defaultInstance = new PlayerLoginDown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerLoginDown)
  }

  public interface PlayerLogoutUpOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code PlayerLogoutUp}
   *
   * <pre>
   *2100003_角色登出
   * </pre>
   */
  public static final class PlayerLogoutUp extends
      com.google.protobuf.GeneratedMessage
      implements PlayerLogoutUpOrBuilder {
    // Use PlayerLogoutUp.newBuilder() to construct.
    private PlayerLogoutUp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerLogoutUp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerLogoutUp defaultInstance;
    public static PlayerLogoutUp getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerLogoutUp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLogoutUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cwa.message.PlayerMessage.internal_static_PlayerLogoutUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cwa.message.PlayerMessage.internal_static_PlayerLogoutUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cwa.message.PlayerMessage.PlayerLogoutUp.class, com.cwa.message.PlayerMessage.PlayerLogoutUp.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerLogoutUp> PARSER =
        new com.google.protobuf.AbstractParser<PlayerLogoutUp>() {
      public PlayerLogoutUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLogoutUp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLogoutUp> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.message.PlayerMessage.PlayerLogoutUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cwa.message.PlayerMessage.PlayerLogoutUp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerLogoutUp}
     *
     * <pre>
     *2100003_角色登出
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cwa.message.PlayerMessage.PlayerLogoutUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLogoutUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLogoutUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cwa.message.PlayerMessage.PlayerLogoutUp.class, com.cwa.message.PlayerMessage.PlayerLogoutUp.Builder.class);
      }

      // Construct using com.cwa.message.PlayerMessage.PlayerLogoutUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cwa.message.PlayerMessage.internal_static_PlayerLogoutUp_descriptor;
      }

      public com.cwa.message.PlayerMessage.PlayerLogoutUp getDefaultInstanceForType() {
        return com.cwa.message.PlayerMessage.PlayerLogoutUp.getDefaultInstance();
      }

      public com.cwa.message.PlayerMessage.PlayerLogoutUp build() {
        com.cwa.message.PlayerMessage.PlayerLogoutUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cwa.message.PlayerMessage.PlayerLogoutUp buildPartial() {
        com.cwa.message.PlayerMessage.PlayerLogoutUp result = new com.cwa.message.PlayerMessage.PlayerLogoutUp(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cwa.message.PlayerMessage.PlayerLogoutUp) {
          return mergeFrom((com.cwa.message.PlayerMessage.PlayerLogoutUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cwa.message.PlayerMessage.PlayerLogoutUp other) {
        if (other == com.cwa.message.PlayerMessage.PlayerLogoutUp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cwa.message.PlayerMessage.PlayerLogoutUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cwa.message.PlayerMessage.PlayerLogoutUp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerLogoutUp)
    }

    static {
      defaultInstance = new PlayerLogoutUp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerLogoutUp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerLoginUp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerLoginUp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerLoginDown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerLoginDown_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerLogoutUp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerLogoutUp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0332100000_PlayerMessage.proto\"3\n\rPlayerL" +
      "oginUp\022\016\n\006userId\030\001 \002(\004\022\022\n\ncreateTime\030\002 \002" +
      "(\004\"9\n\017PlayerLoginDown\022\022\n\nloginState\030\001 \002(" +
      "\r\022\022\n\nlogoutTime\030\002 \002(\004\"\020\n\016PlayerLogoutUp*" +
      "]\n\023PlayerCommondIdEnum\022\025\n\016_PlayerLoginUp" +
      "\020\241\226\200\001\022\027\n\020_PlayerLoginDown\020\242\226\200\001\022\026\n\017_Playe" +
      "rLogoutUp\020\243\226\200\001B \n\017com.cwa.messageB\rPlaye" +
      "rMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PlayerLoginUp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PlayerLoginUp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerLoginUp_descriptor,
              new java.lang.String[] { "UserId", "CreateTime", });
          internal_static_PlayerLoginDown_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PlayerLoginDown_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerLoginDown_descriptor,
              new java.lang.String[] { "LoginState", "LogoutTime", });
          internal_static_PlayerLogoutUp_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PlayerLogoutUp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerLogoutUp_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
